name: Replace Ads and Analytics

on:
  push:
    branches:
      - main

jobs:
  run-php-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0' # Set the desired PHP version here

    - name: Run PHP Script
      run: |
        php replaceAds.php # Runs the PHP script to replace ads/analytics

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Replaced ads and analytics"
        git push
