name: Update Ads and Analytics Scripts

on:
  push:
    branches:
      - main

jobs:
  replace-multiline-ads-and-analytics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y sed

      - name: Remove old ad code block and replace with comment
        run: |
          REMOVE_ADS_FILE="scripts/old_ads.txt"
          
          # Define the comment to replace ads
          MY_ADS="scripts/new_ads.txt"
          
          # Remove the old ad block and replace with the comment
          find . -name "*.html" -exec perl -0777 -pi -e 's/\Q$(cat $REMOVE_ADS_FILE)\E/(cat $MY_ADS)/gs' {} \;


      - name: Replace old analytics code block
        run: |
          # Define file paths for old and new analytics blocks
          OLD_ANALYTICS_FILE="scripts/old_analytics.txt"
          NEW_ANALYTICS_FILE="scripts/new_analytics.txt"
          
          # Escape special characters for sed
          OLD_ANALYTICS=$(sed -e 's/[\/&]/\\&/g' $OLD_ANALYTICS_FILE)
          NEW_ANALYTICS=$(sed -e 's/[\/&]/\\&/g' $NEW_ANALYTICS_FILE)
          
          # Find and replace old analytics with new analytics
          find . -name "*.html" -exec sed -i ":a;N;\$!ba;s/$OLD_ANALYTICS/$NEW_ANALYTICS/g" {} \;

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Replaced old ad and analytics scripts with new ones"
          git push
